# use Ganache's forked mainnet mode as the default network
# NOTE: You don't *have* to do this, but it is often helpful for testing
networks:
  default: ftm-main-fork

# automatically fetch contract sources from Etherscan
autofetch_sources: True

# require OpenZepplin Contracts
dependencies:
  - yearn/yearn-vaults@0.4.3-1sol8
  - OpenZeppelin/openzeppelin-contracts@4.4.1

# path remapping to support imports from GitHub/NPM
compiler:
  solc:
    version: 0.8.12
    remappings:
      - "@yearnvaults=yearn/yearn-vaults@0.4.3-1sol8"
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.4.1"

reports:
  exclude_contracts:
